Set-StrictMode -Version Latest
$script:StateFormat='logicvein-netld-terminal-log-export-state';$script:RunFormat='logicvein-netld-terminal-log-export-run'
function Get-Value($Object,[string]$Name,$Default=$null){if($Object-is[Collections.IDictionary]){if($Object.Contains($Name)){return $Object[$Name]}}elseif($null-ne$Object-and$Object.PSObject.Properties[$Name]){return $Object.$Name};$Default}
function Get-SafeName([string]$Value,[string]$Fallback){$clean=($Value.Trim()-replace'[^A-Za-z0-9._-]+','_').Trim(' ','.','_');if($clean){$clean}else{$Fallback}}
function ConvertFrom-Milliseconds([long]$Value){[DateTimeOffset]::FromUnixTimeMilliseconds($Value).UtcDateTime.ToString('yyyy-MM-ddTHH:mm:ss')}
function Write-AtomicBytes([string]$Path,[byte[]]$Bytes){$directory=Split-Path -Parent $Path;[IO.Directory]::CreateDirectory($directory)|Out-Null;$temporary=Join-Path $directory ".$([IO.Path]::GetFileName($Path)).$([guid]::NewGuid()).tmp";try{[IO.File]::WriteAllBytes($temporary,$Bytes);[IO.File]::Move($temporary,$Path,$true)}finally{if(Test-Path $temporary){Remove-Item $temporary -Force}}}
function Write-AtomicJson([string]$Path,$Value){Write-AtomicBytes $Path ([Text.UTF8Encoding]::new($false).GetBytes(($Value|ConvertTo-Json -Depth 30)+[Environment]::NewLine))}
function Get-TerminalLogState([string]$Path){if(-not(Test-Path $Path)){return [ordered]@{format=$script:StateFormat;formatVersion=1}};$state=Get-Content $Path -Raw|ConvertFrom-Json -AsHashtable;if($state.format-ne$script:StateFormat-or$state.formatVersion-ne 1){throw 'The terminal-log state file has an unsupported format.'};$state}
function Get-TerminalLogSearch($Config,$State){$schemes=[Collections.Generic.List[string]]::new();$queries=[Collections.Generic.List[string]]::new();if($State.Contains('lastSessionEnd')){$schemes.Add('since');$queries.Add((ConvertFrom-Milliseconds ([long]$State.lastSessionEnd)))}else{$schemes.Add('session');$queries.Add($Config.InitialLookback)};if($Config.Networks.Count){$schemes.Add('network');$queries.Add(($Config.Networks-join','))};if($Config.Target){$schemes.Add('target');$queries.Add($Config.Target)};[pscustomobject]@{Scheme=$schemes-join',';Query=$queries-join"`n"}}
function Select-TerminalLogRecords($Records,$State){$ids=@{};foreach($id in @(Get-Value $State 'logIdsAtLastSessionEnd' @())){$ids[[long]$id]=$true};$selected=if(-not$State.Contains('lastSessionEnd')){@($Records)}else{$watermark=[long]$State.lastSessionEnd;@($Records|Where-Object{[long]$_.sessionEnd-gt$watermark-or([long]$_.sessionEnd-eq$watermark-and-not$ids.ContainsKey([long]$_.logId))})};$unique=@{};foreach($record in $selected){$unique[[long]$record.logId]=$record};@($unique.Values|Sort-Object @{Expression={[long]$_.sessionEnd}},@{Expression={[long]$_.logId}})}
function Save-TerminalLog($Config,$Record,[byte[]]$Content){$date=[DateTimeOffset]::FromUnixTimeMilliseconds([long]$Record.sessionStart).UtcDateTime;$directory=Join-Path $Config.OutputDir (Join-Path (Get-SafeName ([string]$Record.managedNetwork) 'network') (Join-Path (Get-SafeName ([string]$Record.ipAddress) 'device') $date.ToString('yyyy-MM-dd')));$stem="$($date.ToString('yyyyMMddTHHmmssZ'))_log-$([long]$Record.logId)";$contentPath=Join-Path $directory ($stem+$(if($Config.StripXml){'.log'}else{'.xml'}));$metadataPath=Join-Path $directory ($stem+'.metadata.json');Write-AtomicBytes $contentPath $Content;Write-AtomicJson $metadataPath ([ordered]@{record=$Record;contentFile=[IO.Path]::GetFileName($contentPath);stripXml=$Config.StripXml});[ordered]@{logId=[long]$Record.logId;sessionStart=[long]$Record.sessionStart;sessionEnd=[long]$Record.sessionEnd;bytes=$Content.Length;contentFile=[IO.Path]::GetRelativePath($Config.OutputDir,$contentPath);metadataFile=[IO.Path]::GetRelativePath($Config.OutputDir,$metadataPath)}}
function Export-TerminalLogData($Config,[scriptblock]$Search,[scriptblock]$Retrieve,[string]$GeneratedAt){$state=Get-TerminalLogState $Config.StatePath;$searchData=Get-TerminalLogSearch $Config $state;$records=@(&$Search $searchData.Scheme $searchData.Query);$candidates=@(Select-TerminalLogRecords $records $state);$archived=[Collections.Generic.List[object]]::new();$failures=[Collections.Generic.List[object]]::new();foreach($record in $candidates){try{$archived.Add((Save-TerminalLog $Config $record ([byte[]](& $Retrieve $record))))}catch{$failures.Add([ordered]@{logId=Get-Value $record 'logId';sessionStart=Get-Value $record 'sessionStart';error=$_.Exception.Message})}};if($candidates.Count-and-not$failures.Count){$newest=($candidates|ForEach-Object{[long]$_.sessionEnd}|Measure-Object -Maximum).Maximum;$ids=@($candidates|Where-Object{[long]$_.sessionEnd-eq$newest}|ForEach-Object{[long]$_.logId});if($state.Contains('lastSessionEnd')-and[long]$state.lastSessionEnd-eq$newest){$ids+=@(Get-Value $state 'logIdsAtLastSessionEnd' @())};$state.lastSessionEnd=[long]$newest;$state.logIdsAtLastSessionEnd=@($ids|Sort-Object -Unique)};if(-not$GeneratedAt){$GeneratedAt=[DateTime]::UtcNow.ToString('yyyy-MM-ddTHH:mm:ssZ')};$report=[ordered]@{format=$script:RunFormat;formatVersion=1;generatedAt=$GeneratedAt;scheme=$searchData.Scheme;resultCount=$records.Count;archivedCount=$archived.Count;failureCount=$failures.Count;archived=@($archived);failures=@($failures)};Write-AtomicJson $Config.StatePath $state;Write-AtomicJson $Config.ReportPath $report;$report}
function Invoke-NetLDRpc($Connection,[string]$Method,$Parameters){$body=@{jsonrpc='2.0';method=$Method;params=$Parameters;id=[guid]::NewGuid().ToString()}|ConvertTo-Json -Depth 20;$response=Invoke-WebRequest -Uri "$($Connection.BaseUrl)/rest" -Method Post -Headers @{Authorization="Bearer $($Connection.ApiKey)";'Content-Type'='application/json'} -Body $body -WebSession $Connection.Session -MaximumRedirection 0 -TimeoutSec 30;$data=$response.Content|ConvertFrom-Json;$errorProperty=$data.PSObject.Properties['error'];if($errorProperty-and$errorProperty.Value){throw"$Method failed: $($errorProperty.Value|ConvertTo-Json -Compress -Depth 10)"};$data.result}
function Invoke-ExportTerminalLogs($Config){$session=New-Object Microsoft.PowerShell.Commands.WebRequestSession;Invoke-WebRequest -Uri "$($Config.BaseUrl)/rest" -Headers @{Authorization="Bearer $($Config.ApiKey)"} -WebSession $session -MaximumRedirection 0 -TimeoutSec 30|Out-Null;$connection=@{BaseUrl=$Config.BaseUrl;ApiKey=$Config.ApiKey;Session=$session};$search={param($scheme,$query)@(Invoke-NetLDRpc $connection 'TermLogs.search' @($scheme,$query,'sessionEnd',$false))};$retrieve={param($record)$parameters=@{op='content';stripXml=$Config.StripXml.ToString().ToLowerInvariant();sessionStart=ConvertFrom-Milliseconds ([long]$record.sessionStart);ipAddress=$record.ipAddress;managedNetwork=$record.managedNetwork};$response=Invoke-WebRequest -Uri "$($Config.BaseUrl)/servlet/termlog" -Headers @{Authorization="Bearer $($Config.ApiKey)"} -Body $parameters -WebSession $session -Method Get -MaximumRedirection 0 -TimeoutSec 30;return ,([byte[]]$response.RawContentStream.ToArray())};Export-TerminalLogData $Config $search $retrieve}
Export-ModuleMember -Function Export-TerminalLogData,Get-TerminalLogSearch,Select-TerminalLogRecords,Invoke-ExportTerminalLogs
